# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutations.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmutations.proto\"l\n\x0e\x42\x65liefMutation\x12\x1e\n\x02op\x18\x01 \x01(\x0e\x32\x12.BeliefMutation.Op\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"\x19\n\x02Op\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01\"c\n\x0cPlanMutation\x12\x1c\n\x02op\x18\x01 \x01(\x0e\x32\x10.PlanMutation.Op\x12\x0c\n\x04prio\x18\x02 \x01(\r\x12\x0c\n\x04plan\x18\x03 \x01(\t\"\x19\n\x02Op\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mutations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BELIEFMUTATION']._serialized_start=19
  _globals['_BELIEFMUTATION']._serialized_end=127
  _globals['_BELIEFMUTATION_OP']._serialized_start=102
  _globals['_BELIEFMUTATION_OP']._serialized_end=127
  _globals['_PLANMUTATION']._serialized_start=129
  _globals['_PLANMUTATION']._serialized_end=228
  _globals['_PLANMUTATION_OP']._serialized_start=102
  _globals['_PLANMUTATION_OP']._serialized_end=127
# @@protoc_insertion_point(module_scope)
